[config]
schemaVersion = "0.0.1"

[package]
namespace = "Conductor"
name = "MoreBosses_Reloaded"
versionNumber = "0.1.0"
description = "Mod with new Boss variants"
websiteUrl = "https://github.com/Monster-Train-2-Modding-Group/MoreBosses-Reloaded"
containsNsfwContent = false

[package.dependencies]
BepInEx-BepInExPack = "5.4.2100"
MT2-Trainworks_Reloaded = "0.5.0"

[build]
icon = "./icon.png"
readme = "./README.md"
outdir = "./"

[[build.copy]]
source = "./plugin_build"
target = ""

[publish]
repository = "https://thunderstore.io"
communities = [ "monster-train-2" ]


